Vagrant.configure("2") do |config|
  config.vm.define "web" do |web|
    web.vm.box = "bento/ubuntu-22.04"
    web.vm.box_check_update = false
    web.vm.network "forwarded_port", guest: 8086, host: 8086 
    web.vm.network "private_network", ip: "192.168.33.11"
    web.vm.synced_folder "./web", "/vagrant_data"

    web.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "1024"
      vb.name = "web"
    end
  end
end
